version: '3'
networks:
  app-tier:
    driver: bridge
services:
  prometheus:
    container_name: prometheus
    image: 'prom/prometheus'
    restart: always
    hostname: prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus:/data
    networks:
      - app-tier
  grafana:
    container_name: grafana
    image: 'grafana/grafana'
    restart: always
    hostname: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana:/data
    networks:
      - app-tier
  my-app:
    image: 'spring-boot-prometheus-grafana.jar:latest'
    ports:
      - '8080:8080'
    networks:
      - app-tier
    depends_on:
      - prometheus
      - grafana
volumes:
  prometheus:
    driver: local
  grafana:
    driver: local